
# platform: win-64
# created-by: conda 24.9.2

name: mydjangoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - werkzeug==3.1.3
      - wheel==0.44.0
      - zipp==3.21.0
      - tzdata==2024.2
      - typing_extensions==4.11.0
      - six==1.16.0
      - shapely==2.0.6
      - python-dotenv==1.0.1
      - python-decouple==3.8
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyscopg2==2.9.9
      - pip==24.2
      - packaging==24.2
      - numpy==2.0.2
      - pandas==2.2.3
      - psycopg2==2.9.9
      - geos==3.13.0
      - geopandas==1.0.1
      - flask-cors==5.0.0
      - flask==3.1.0
      - djangorestframework==3.15.2
      - django-leaflet==0.31.0
      - django-environ==0.11.2
      - django==4.2.17
      - cryptography==44.0.0
      - colorama==0.4.6
      - click==8.1.7
      - cffi==1.17.1
  - geos
  - gdal
  - numpy
  - libpq
  - libcurl
  - libxml2
  - libiconv
  - libtiff
  - libpng
  - libsqlite
  - sqlite
  - libdeflate
  - pyproj
  - liblzma
  - libssh2
  - libspatialite
  - lz4-c
  - libgdal-core
  - lzo
  - blosc
  - bzip2
  - _libavif_api
  - dav1d
  - aom
  - minizip
  - zlib
  - zstd
  - tbb
  - svt-av1
  - rttopo
  - shapely
  - pycparser
  - importlib-metadata
  - asgiref
  - gunicorn
  - pyogrio
  - paramiko
  - geotiff
  - geos
