name: mydjangoenv  # Name of the environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip  # Ensure pip is available
  - gdal=3.10.0
  - geopandas
  - geos
  - libpq
  - psycopg2
  - libcurl
  - libxml2
  - pyproj
  - sqlite
  - tzdata
  - typing_extensions
  - zlib
  - zstd
  - tbb
  - x265
  - svt-av1
  - shapely
  - numpy
  - pandas
  - flask
  - pip:
      - bcrypt==4.2.1
      - blinker==1.9.0
      - certifi==2024.12.14
      - click==8.1.7
      - colorama==0.4.6
      - cryptography==44.0.0
      - django==4.2.17
      - django-environ==0.11.2
      - django-leaflet==0.31.0
      - djangorestframework==3.15.2
      - flask-cors==5.0.0
      - gunicorn==23.0.0
      - importlib-metadata==8.5.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - markupsafe==3.0.2
      - paramiko==3.5.0
      - python-dateutil==2.9.0.post0
      - python-decouple==3.8
      - python-dotenv==1.0.1
      - pytz==2024.2
      - werkzeug==3.1.3
      - wheel==0.44.0
      - zipp==3.21.0
