name: flood_watch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pip
  - geopandas=1.0.1
  - gdal=3.10.0
  - django=4.1
  - flask=3.1.0
  - pandas=2.2.3
  - numpy=2.0.2
  - pip:
    - werkzeug==3.1.3
    - zipp==3.21.0
    - tzdata==2024.2
    - pytz==2024.2
    - shapely==2.0.6
    - rav1e==0.6.6
    - six==1.16.0
