# Generated by Django 4.1 on 2024-12-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impacts',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
