# Generated by Django 5.1.4 on 2025-01-07 06:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedCrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('engtype_1', models.CharField(max_length=80)),
                ('lack_cc', models.FloatField()),
                ('cod', models.CharField(max_length=80)),
                ('stock', models.FloatField()),
                ('flood_tot', models.FloatField()),
                ('flood_perc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'AffectedCrops',
            },
        ),
        migrations.CreateModel(
            name='AffectedGrazingLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('engtype_1', models.CharField(max_length=80)),
                ('lack_cc', models.FloatField()),
                ('cod', models.CharField(max_length=80)),
                ('stock', models.FloatField()),
                ('flood_tot', models.FloatField()),
                ('flood_perc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'AffectedGrazingLand',
            },
        ),
        migrations.CreateModel(
            name='AffectedLivestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('engtype_1', models.CharField(max_length=80)),
                ('lack_cc', models.FloatField()),
                ('cod', models.CharField(max_length=80)),
                ('stock', models.FloatField()),
                ('flood_tot', models.FloatField()),
                ('flood_perc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'AffectedLivestock',
            },
        ),
        migrations.CreateModel(
            name='AffectedPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('engtype_1', models.CharField(max_length=80)),
                ('lack_cc', models.FloatField()),
                ('cod', models.CharField(max_length=80)),
                ('stock', models.FloatField()),
                ('flood_tot', models.FloatField()),
                ('flood_perc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'AffectedPopulation',
            },
        ),
        migrations.CreateModel(
            name='AffectedRoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('engtype_1', models.CharField(max_length=80)),
                ('lack_cc', models.FloatField()),
                ('cod', models.CharField(max_length=80)),
                ('stock', models.FloatField()),
                ('flood_tot', models.FloatField()),
                ('flood_perc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'AffectedRoads',
            },
        ),
        migrations.CreateModel(
            name='DisplacedPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('engtype_1', models.CharField(max_length=80)),
                ('lack_cc', models.FloatField()),
                ('cod', models.CharField(max_length=80)),
                ('stock', models.FloatField()),
                ('flood_tot', models.FloatField()),
                ('flood_perc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'DisplacedPopulation',
            },
        ),
        migrations.CreateModel(
            name='ImpactedGDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('engtype_1', models.CharField(max_length=80)),
                ('lack_cc', models.FloatField()),
                ('cod', models.CharField(max_length=80)),
                ('stock', models.FloatField()),
                ('flood_tot', models.FloatField()),
                ('flood_perc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'ImpactedGDP',
            },
        ),
    ]
