"""flood_watch_system URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    # Admin route: Access the Django admin panel
    path('admin/', admin.site.urls), 
    

    # API routes: Includes all URLs from the 'Impact' app, which are handled by DRF ViewSets
    # This means the API routes for things like affected population, GDP, crops, etc. will be handled here.
    path('api/', include('Impact.urls')),

    # path('', include('wagtail.urls')),  # Wagtail

    # API Schema generation routes (for API documentation tools): These routes are used to generate API documentation
    # SpectacularAPIView: This endpoint generates the OpenAPI schema for your API
    # This schema describes all the endpoints and is used by other tools to generate API documentation.
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Swagger UI: A popular tool for API documentation that provides an interactive web UI
    # This endpoint will serve the Swagger UI based on the OpenAPI schema generated by SpectacularAPIView.
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

    # ReDoc: Another tool for displaying API documentation. It presents the schema in a clean, user-friendly format.
    # This endpoint serves the ReDoc UI based on the same OpenAPI schema.
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]
