name: Django CI/CD with Conda and pip (Staging)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-conda:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Miniconda and set up the environment
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: 'latest'
          activate-environment: 'mydjangoenv'
          environment-file: environment.yml
          channels: conda-forge
        env:
          CONDA_PKGS_DIRS: "./conda_pkgs"

      # Step 3: Install additional pip dependencies
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run database setup
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql
          sudo service postgresql start

      # Step 5: Apply migrations and run tests
      - name: Apply migrations and run tests
        run: |
          python manage.py migrate
          python manage.py test

      # Step 6: Collect static files
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      # Step 7: Lint code
      - name: Lint code
        run: |
          flake8 .
